service: authorization-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

resources:
  Outputs:
    basicAuthorizerArn:
      Value:
        'Fn::GetAtt': ['BasicAuthorizerLambdaFunction', 'Arn']                

plugins:
  - serverless-webpack
  - serverless-aws-documentation

custom:
  webpack:
    webpackConfig: '../../webpack.config.js'
    includeModules: true

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
